version: '3'
services:
  
  #Database MySql
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
       - db_data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: 2ndMilestoneESII
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
    networks:
      - wpsite  

  #phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '7000:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - wpsite

  #WordPress CMS
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    restart: always
    volumes: ['./Wordpress/wp-content:/var/www/html/wp-content'] 
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: 2ndMilestoneESII
    ports:
      - 8000:80
    networks:
      - wpsite

networks:
  wpsite:
volumes:
  db_data: